### ISSUE TITLE
Selenium Builder 3.05 Not implemented yet

### ISSUE THREAD

**Issue by nickyipee** [SeleniumBuilder/selenium-builder#8]
Hi I have been using an older version of Builder for a while now. recently I setup a new machine and installed the builder 3.05 plugin. However if I try and run a test I receive the message Not implemented yet. grateful for your help.

**Comment by Zarkonnen** [comment]
Yes, I'm afraid local playback had to be removed because it was not compatible with Firefox's new, more stringent requirements for addons. I have started work on re-implementing local playback from scratch.

Remote playback still works fine, so the best workaround for now is to run a selenium server locally and use it for playback. Let me know if you'd like more detailed instructions on that.
